### PR TITLE
add cocoapods support

### PR DESCRIPTION
**Pull request by triznakj**
Also removes the `Pods` file from the `.gitignore`.

### CODE REVIEW

**Comment by JagCesar** [comment]
Cool! Thanks so much spending time on this @triznakj! Did you try this out to make sure it works?

~Also, would you mind rebasing based on `develop` so the build passes on our CI?~

Edit: Nvm, our CI built `develop` and added your changes :)

**Review by westerlund — CHANGES_REQUESTED** [review]
Hey @triznakj! Great initiative, but I think you've implemented CocoaPods the other way around, adding CocoaPods _to_ the project, not making the project usable from CocoaPods. When adding support for CocoaPods you add a `podspec` file.

You can read more about it here: https://guides.cocoapods.org/syntax/podspec.html and https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by westerlund** [comment]
This PR will fix #25

**Comment by JagCesar** [comment]
Closing issue, this does not add cocoa pods support.

**Pull request closed without merging**
